library(ggplot2)
library(ggcorrplot)
library(corrplot)
library(corrgram)
library(pheatmap)

data <- read.csv("./相关系数表.csv")
mat <- cor(data)
corrplot(mat)
corrplot(mat, method = "number", outline = F, add = TRUE, type = "lower", order = "hclust", addrect = 2, col = "black", diag = FALSE, tl.pos = "n")
